### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by skoyah** [skoyah/unit-converter#8]
Add extra functionality so the package can be integrated in Laravel applications.

**Comment by josepostiga** [comment]
Care to describe a little more on what is intended, here?

**Comment by skoyah** [comment]
Hey @josepostiga. This was long time ago! :) I was still learning the fundamentals of Laravel and thought I would need to to something in order to work properly with the framework.

So, for now I think this issue will be closed.

Thanks for getting in touch! ;)
